### ISSUE TITLE
Need mounting hole dimensions

### ISSUE THREAD

**Issue by kitchung** [bigtreetech/SKSM#1]
Current documentation is lacking official mounting hole dimensions.

**Comment by Sprocyon** [comment]
DIN rail mounting would also be nice.

**Comment by looxonline** [comment]
STEP files are provided which contain dimensions of all parts.

DIN mounts have been uploaded in STEP and STL.

**Comment by Sprocyon** [comment]
BIGTREETECH SKSM V1.0.step Does not contain any holes.

**Comment by looxonline** [comment]
> BIGTREETECH SKSM V1.0.step Does not contain any holes.

Fixed. Thanks for pointing it out.
